apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocr-app-pvc
  namespace: ocr-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocr-data-pvc
  namespace: ocr-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
